export const PAGE_ENVIRONMENT = {
  dashboard: "loggro",
  cierre_turno: "loggro",
  cierre_turno_anteriores: "loggro",
  historico_cierre_turno: "loggro",
  cierre_inventarios: "loggro",
  historico_cierre_inventarios: "loggro",
  configuracion: "loggro",
  loggro: "loggro",
  visualizacion_cierre_turno: "loggro",
  visualizacion_cierre_turno_historico: "loggro",
  visualizacion_cierre_inventarios: "loggro",
  visualizacion_cierre_inventarios_historico: "loggro",
  inventarios: "loggro",
  permisos: "loggro",
  registro_empleados: "loggro",
  registro_otros_usuarios: "loggro",
  gestion_usuarios: "loggro",
  gestion_empresas: "loggro",
  facturacion: "siigo",
  dashboard_siigo: "siigo",
  configuracion_siigo: "siigo",
  subir_facturas_siigo: "siigo",
  historico_facturas_siigo: "siigo",
  nomina: ["siigo", "loggro"]
};

export const DEFAULT_ROLE_PERMISSIONS = {
  admin_root: {
    dashboard: true,
    cierre_turno: true,
    cierre_turno_anteriores: true,
    historico_cierre_turno: true,
    cierre_inventarios: true,
    historico_cierre_inventarios: true,
    configuracion: true,
    loggro: true,
    visualizacion_cierre_turno: true,
    visualizacion_cierre_turno_historico: true,
    visualizacion_cierre_inventarios: true,
    visualizacion_cierre_inventarios_historico: true,
    inventarios: true,
    permisos: true,
    registro_empleados: true,
    registro_otros_usuarios: true,
    gestion_usuarios: true,
    gestion_empresas: true,
    facturacion: true,
    dashboard_siigo: true,
    configuracion_siigo: true,
    subir_facturas_siigo: true,
    historico_facturas_siigo: true,
    nomina: true
  },
  admin: {
    dashboard: true,
    cierre_turno: true,
    cierre_turno_anteriores: true,
    historico_cierre_turno: true,
    cierre_inventarios: true,
    historico_cierre_inventarios: true,
    configuracion: false,
    loggro: true,
    visualizacion_cierre_turno: true,
    visualizacion_cierre_turno_historico: true,
    visualizacion_cierre_inventarios: true,
    visualizacion_cierre_inventarios_historico: true,
    inventarios: true,
    permisos: false,
    registro_empleados: false,
    registro_otros_usuarios: false,
    gestion_usuarios: false,
    gestion_empresas: false,
    facturacion: true,
    dashboard_siigo: true,
    configuracion_siigo: false,
    subir_facturas_siigo: true,
    historico_facturas_siigo: true,
    nomina: true
  },
  revisor: {
    dashboard: true,
    cierre_turno: true,
    cierre_turno_anteriores: true,
    historico_cierre_turno: true,
    cierre_inventarios: true,
    historico_cierre_inventarios: true,
    configuracion: false,
    loggro: false,
    visualizacion_cierre_turno: false,
    visualizacion_cierre_turno_historico: false,
    visualizacion_cierre_inventarios: false,
    visualizacion_cierre_inventarios_historico: false,
    inventarios: true,
    permisos: false,
    registro_empleados: false,
    registro_otros_usuarios: false,
    gestion_usuarios: false,
    gestion_empresas: false,
    facturacion: false,
    dashboard_siigo: true,
    configuracion_siigo: false,
    subir_facturas_siigo: false,
    historico_facturas_siigo: true,
    nomina: false
  },
  operativo: {
    dashboard: false,
    cierre_turno: true,
    cierre_turno_anteriores: true,
    historico_cierre_turno: false,
    cierre_inventarios: true,
    historico_cierre_inventarios: false,
    configuracion: false,
    loggro: false,
    visualizacion_cierre_turno: false,
    visualizacion_cierre_turno_historico: false,
    visualizacion_cierre_inventarios: false,
    visualizacion_cierre_inventarios_historico: false,
    inventarios: false,
    permisos: false,
    registro_empleados: false,
    registro_otros_usuarios: false,
    gestion_usuarios: false,
    gestion_empresas: false,
    facturacion: false,
    dashboard_siigo: false,
    configuracion_siigo: false,
    subir_facturas_siigo: false,
    historico_facturas_siigo: false,
    nomina: false
  }
};

export const PERMISSIONS = Object.fromEntries(
  Object.keys(PAGE_ENVIRONMENT).map((moduleKey) => [
    moduleKey,
    Object.entries(DEFAULT_ROLE_PERMISSIONS)
      .filter(([, modules]) => modules?.[moduleKey] === true)
      .map(([role]) => role)
  ])
);
